from autokeras_pretrained.object_detector import ObjectDetector
from autokeras_pretrained.face_detector import FaceDetector
from autokeras_pretrained.voice_generator.voice_generator import VoiceGenerator
from autokeras_pretrained.voice_recognizer import VoiceRecognizer