language: python
python:
- '3.6'
install:
- pip install -r requirements.txt --quiet
- pip install pytest
- pip install pytest-cov
- pip install coverage
script:
- pytest tests --cov=autokeras_pretrained --cov-report xml:coverage.xml
after_success:
- pip install python-coveralls && coveralls
deploy:
  provider: pypi
  user: jhfjhfj1
  on:
    tags: true
    repo: jhfjhfj1/autokeras-pretrained
  password:
    secure: n17FmmcgJzRAEPAMn/OpcdVu5T6nq+Fh+CgNDruaJI3EP4doyjsP/lu6NRsEwCdWfVC0+m4eAgULL3gMHHv3cCGH96T4S1pYGZGZ0ukPcMhm9aOyewg/Fxq6uGSP1h/xEaV7J4+ph8WKRF6J/2jnDwbQeIu//uOMkH5wGBRh6dUARN14fmpsCisDM0wDgGZtnD2bjfHtnaP0PkcBpG7XdjWHPOCMdrc4wl5frykUGO/aRFklfw4qQPC/K/46NPUneAO7IsmEfC8Fg9IjA5SXX7hnDTap8GbP9lCrDGRMpM0K4nay7tV+5lhDwh1I4Xw9kmwbLF3Y889pj3EEYiVyALsRzQKlOE37O5i0N5XbfLUtvDE4ugS++Zg0Wa7J1jV22xhIJ36xf1PBfW65G9ixPu/7DMPUrdDlKkYkVInMyRZAPgGo/94FxnBw3dHvUke6BhRgEPWfkcoFXvMu7e7l2JEg3bmWeYXALZJTP5KGo3ShE3OdfoSuhrDQm7TRpWZnGTxz+ua3BqBWPiuOvONt2RS46BX4fTlNZFjiHdaZ2a18pav7QT1bVZWSS5Op3GssZtWS+kepdya+Ts+7Tfr1EmEBuuHENhV48mI4Pc9SfJCXTnHkLM58FrYX7RIOqCQnPu1lGuiQwKFB6LPF3rznDvIiKZhd1wbKdb6ie6+A+BU=
