language: python
python:
- '3.6'
install:
- pip install -r requirements.txt --quiet
- pip install pytest
- pip install pytest-cov
- pip install coverage
- pip install codacy-coverage
script:
- pytest tests --cov=autokeras_pretrained --cov-report xml:coverage.xml
after_script:
- python-codacy-coverage -r coverage.xml
deploy:
- provider: pypi
  user: jhfjhfj1
  password:
    secure: B36Cg4YbMhIrHyi1LAxilS2fek905PAyU+0anw8BTWgjOF0oM7hLRb64LcgpHrp6E0VawIscE7KGfCaiJR+14S3gqO2blaiJ0Os+ovpbzSu8sAnBVVKfT8Lv24o7prxeq2G8UROXPDST2ZEhy4rugCFjNeMv65WSezpG08TJasmvUAySidQU7rvzoIgoEiKkc7329bzaHpWVQDyuXs/slQSufTK23WBA+OM3cclLrQE02wVH0q/+BtjvkN+44XOVM7Q/gmIrVndj8KGVTIFPYjmKuIiyxjcSGv67oQhXNRH/SSOJyMb93elu/o4y7zexG8eZ2BVr0+Q2pkyBo8JAmfuuWLnz0gONwfU4xwMlLy2m/muGDclMr9eC1i0KWOG0E7afbktFXMVG9EBWr19OPApqGvtfU4997sPUcx7hDFLAwLyznR1hOFIKbeSdtFSUUfGoCnzrCcobsJkD1QKGLoPwr0/gp5o+HJC0bLyMSo45ETsH1m5UGFgFO9Xk4KiGQndL0SpSq7VfZxnMVJttRObqq/8/4wwgFBp8p/bXPpkoS5NK5QajdQgTZ2u8O5SABDBStMq2rdsLdqX4/1tyBcG+u8cKiXjJOfn3chVAwJUNTgddlOa6aGZFM1h3qB8WHgIYJjWxygAKfnH14XRDPAbeEvGdXfwZhJqLfFo6rQs=
  on:
    tags: true
    repo: jhfjhfj1/autokeras-pretrained
env:
  global:
    secure: 0ZmkjLmGZnZSjZplHjm/1x2izv+OC+/S+/jUWaSNGZvHBtGRwsf1EHi65RzkCD9V8YCN42HE3SFh+mEN5nVaYPzxMvhnzrXVzce8oAU8o0qmCTh1K3d74KTzHtJdQGxCZi6KjAhkIZdQclR8FkTnU629BbDGMJ+MCm1imcawyI4ooXFpkCPsa0l+U9A8gZ47/FdKK7lP3Idw/dvIAcU6Cx1+hhkpmyWLqPiig2vB6vYFPYbrRvw2YCkvhhQoADT9pREK9vfYBf/1F9LOt00MAPXcHT/mjok7ziEiqQIrns2sa8CumEX9nUhaTq4TliMxPFDCvKxtMq4+cO5/slr6xD/Nh5hURUjaKytRJG44FmonqBOqKB7Zo3pgRF5/gY6YGUapuh+C2suTQmsJxwXCsG64sFk9SGmpqOImbfvivxxEhcXl7TGQNn7UNH1fxwrklkSj1B84BBnTIDwgAAFQS+4JlHSGo5KAZZwXCzPh0j+6KR2TdPLsrhqm1JIYRDqI8Jq4EkZICSGIjKO52XYq1Hrl+9uudoy6+rvQXlEQz/Pj/jj9DwATt1keqjk8p9Xinnw7X+h0nD+Q2Wtfn6LCzH+E3rDrlpdBRtWhnI37aZHiLwovmqDiMwxY76SsEm5XDsFKABYXxvoiXT5IVHqVd7tEveZR1l+N8mN53B5Q8Z0=
